### ISSUE TITLE
install for v1.2.0 breaks at the beginning

### ISSUE THREAD

**Issue by jayhohoho2019** [Chia-Network/bladebit#114]
what should git clone?

**Comment by jonathan-adams-fullstack** [comment]
git clone https://github.com/Chia-Network/bladebit.git

**Comment by jayhohoho2019** [comment]
ok thanks. that works.  probably should fix readme

**Comment by harold-b** [comment]
Thanks for letting me know, had not noticed that was missing.

**Comment by harold-b** [comment]
Fixed
