### ISSUE TITLE
��j (invalid encoding) for plot file name and destination path not respected

### ISSUE THREAD

**Issue by TheOzzOne** [Chia-Network/bladebit#122]
Unsure what or why this has started happening as I have changed nothing on my system. Also unsure why these problems appear to be interlinked. 

bladebit dumps the plot it's creating into the same directory where bladebit resides, with "��j (invalid encoding)" as the file name. 
![image](https://user-images.githubusercontent.com/15208183/136619303-eb43b76e-f016-4a87-93a7-0d4582bc9fdb.png)

bladebit confirmed the output path when it started.
![image](https://user-images.githubusercontent.com/15208183/136618619-37092aa7-c0ea-4a34-8e84-89e4655fa4b1.png)

Happy to provide screenshots, system specs, etc. 
OS: RHEL 8
Proc: 2x Epyc 7451 24c/48t (48c/96t total)
RAM: 704gb 2133 RDIMM
Destination drives are 4x SAS 900GB drives in Raid0.

**Comment by harold-b** [comment]
Very strange. What is the system's locale?

**Comment by harold-b** [comment]
Not ideal though... I'd like to know what caused this. 
Please let me know if you find out any more info related to this issue.
