### ISSUE TITLE
My plots don't appear to count towards pool plots in the Chia GUI

### ISSUE THREAD

**Issue by TheOzzOne** [Chia-Network/bladebit#125]
Unsure if this is related to the issue(s) in #122 where I reported bladebit stopped respecting destination file path. 

It no longer appears that bladebit respects the pool contract address via the -c flag, all of the plots I have made appear to be solo plots, and no longer count toward my pool total in the Chia GUI, although they still appear to be valid plots, but not associated to an NFT.

Plots created with MadMax still appear to increase the count of plots, leading me to believe it's not a Chia GUI issue. 

I am unsure how to test or prove this further, but happy to help troubleshoot in any way that I can.

**Comment by guitengyue** [comment]
I ran into this problem just like you

**Comment by harold-b** [comment]
> how can I modify the file permissions?

Sorry, looks like you're on windows. I assumed Linux. 

The logged output comes from [chiapos's DiskProver at this line](https://github.com/Chia-Network/chiapos/blob/main/src/prover_disk.hpp#L61). It simply fails to open the file using a standard input stream. That is, it is not anything bladebit-related. Something is happening in your setup where chia does not have the ability to open files on that network-mapped path.

**Comment by harold-b** [comment]
Got it, the backslashes made me assume otherwise.

In which case, if it's a permissions issue you'll have to ensure they are readable by the same user running chia by using [chmod](https://linux.die.net/man/1/chmod) and [chown](https://man7.org/linux/man-pages/man2/chown.2.html).

Could be something like:
```bash
sudo chown USER:USER PLOT_FILE
sudo chmod 440 PLOT_FILE
```

Where `USER` is the user running the chia process and `PLOT_FILE` is the plot file path.

**Comment by guitengyue** [comment]
> Got it, the backslashes made me assume otherwise.
> 
> In which case, if it's a permissions issue you'll have to ensure they are readable by the same user running chia by using [chmod](https://linux.die.net/man/1/chmod) and [chown](https://man7.org/linux/man-pages/man2/chown.2.html).
> 
> Could be something like:
> 
> ```shell
> sudo chown USER:USER PLOT_FILE
> sudo chmod 440 PLOT_FILE
> ```
> 
> Where `USER` is the user running the chia process and `PLOT_FILE` is the plot file path.

i slove it. thank you very much!
