### ISSUE TITLE
Use 32c64t (2.5GHz) and 36c72t (3.2GHz) the same speed

### ISSUE THREAD

**Issue by guitengyue** [Chia-Network/bladebit#135]
Question one：
e2683v4 x2(32c64t,2500Mhz), 16x32g ddr4 2133, total 11-12min
e2696v3 x2(36c72t,3200Mhz(I use the e5 bug)),16x32g ddr4 2133, also total 11-12min

Question two：
And I find when use 16x32g,the memry read and write have more then 100GB/s, when I use 14x32g,the memery read and write only have 50GB/s, bug the total time is the same 11-12min.....

**Comment by harold-b** [comment]
Moving this to discussions.

It would be too hard to tell without any extra info, and testing. But you might try a straight memory read/write test between both system to see if you see the same discrepancy.
