### ISSUE TITLE
bladebit-v1.2.3-centos-x86-64.tar.gz reports wrong --version "1.2.0"

### ISSUE THREAD

**Issue by bladeuserpi** [Chia-Network/bladebit#144]
Hi,

1) Problem:
The precompiled asset "bladebit-v1.2.3-centos-x86-64.tar.gz" reports the wrong version:

user@x ~]$ tar tvfz bladebit-v1.2.3-centos-x86-64.tar.gz
-rwxr-xr-x root/root   3652112 2021-11-11 02:10 bladebit

[user@x ~]$ tar xvfz bladebit-v1.2.3-centos-x86-64.tar.gz
bladebit

[user@x ~]$ ./bladebit --version
1.2.0

-> Should be: 1.2.3

2) Additional Info:
The ubuntu asset shows the correct version:
[user@x ~]$ tar tvfz bladebit-v1.2.3-ubuntu-x86-64.tar.gz 
-rwxr-xr-x runner/docker 4568040 2021-11-11 02:10 bladebit

[user@x ~]$ tar xvfz bladebit-v1.2.3-ubuntu-x86-64.tar.gz
bladebit

[user@x ~]$ ./bladebit --version
1.2.3

-> works as expected

3) Conclusion: this problem only affects the centos build, but not the ubuntu build

**Comment by harold-b** [comment]
Thanks for another good report. 
Looks like a CI issue that was present in windows is also on other OSs. 
Will get it fixed.

**Comment by harold-b** [comment]
Fixed in (v.1.2.4)[https://github.com/Chia-Network/bladebit/releases/tag/v1.2.4]
