### ISSUE TITLE
Debian 10.11 vs Ubuntu 20.04 Bladebit times

### ISSUE THREAD

**Issue by RobbieL811** [Chia-Network/bladebit#159]
I'm having some trouble. I just reinstalled my server with a clean Ubuntu 20.04 installation. Coming from Debian 10.11 IIRC. My plot times have increased dramatically! Hoping that one of you might have the answer I'm looking for. On Debian, I was averaging 15-16 minute plot times with Bladebit. On the latest Ubuntu, and latest Bladebit, times have jumped up to 24 mintues per plot. Have any of you ever seen something like this? Where should I even begin to look?

**Comment by wtfiwinomgs** [comment]
> I'm having some trouble. I just reinstalled my server with a clean Ubuntu 20.04 installation. Coming from Debian 10.11 IIRC. My plot times have increased dramatically! Hoping that one of you might have the answer I'm looking for. On Debian, I was averaging 15-16 minute plot times with Bladebit. On the latest Ubuntu, and latest Bladebit, times have jumped up to 24 mintues per plot. Have any of you ever seen something like this? Where should I even begin to look?

on my ubuntu 20.04 it is 16 mins per plot, what are the specs of your system.

**Comment by RobbieL811** [comment]
> > I'm having some trouble. I just reinstalled my server with a clean Ubuntu 20.04 installation. Coming from Debian 10.11 IIRC. My plot times have increased dramatically! Hoping that one of you might have the answer I'm looking for. On Debian, I was averaging 15-16 minute plot times with Bladebit. On the latest Ubuntu, and latest Bladebit, times have jumped up to 24 mintues per plot. Have any of you ever seen something like this? Where should I even begin to look?
> 
> on my ubuntu 20.04 it is 16 mins per plot, what are the specs of your system.

I’m on a 2x e5-2690 v2 with 512 GB of 1866 LRDIMMS. I did another clean reinstall of Debian 11 last night and plot creation times are back to under 16 minutes. Around 15.2 minutes per plot. There’s definitely something going on with Ubuntu. Ubuntu = 22 minutes, Debian = 15.2 minutes. Both clean installations.

**Comment by harold-b** [comment]
I am not sure as to what could be going on re Ubuntu vs Debian, but there does seem to be something going with different distros, there was a discussion before talking about it. Best times seem to come out in RHEL-based distros. CentOS has really good times.

**Comment by harold-b** [comment]
I think this was the thread here: https://github.com/Chia-Network/bladebit/discussions/147

Unsure yet about why the discrepancies, my initial thoughts were that it had to do with the compiler used, but the user clarified that he discarded that possibility. So for now we're unsure, but I suspect it has to do with the way memory pages are handled (which I don't know why it would be different between distros), since CentOS seems to claim and clear them very fast in some tests I had done.

**Comment by wtfiwinomgs** [comment]
> > I am not sure as to what could be going on re Ubuntu vs Debian, but there does seem to be something going with different distros, there was a discussion before talking about it. Best times seem to come out in RHEL-based distros. CentOS has really good times.
> 
> Any idea of a link to where I could go read about it? Debian is producing really good plot times for me. Seems odd to me as I thought Debian and Ubuntu were really close to being the same? Anyways, I’m up and running on latest Debian now and I am happy with it! Keep up the good work and also thanks for your contribution! I don’t mean to sound like I’m in here whining about my plot times. Just wanted to bring it to your attention. I didn’t know it had already been discussed.

if I may ask, where did you get debian 10 or v11? I'd like to try to see if I can replicate the difference in performance. currently ubuntu 20.04 as well.

**Comment by RobbieL811** [comment]
> > > I am not sure as to what could be going on re Ubuntu vs Debian, but there does seem to be something going with different distros, there was a discussion before talking about it. Best times seem to come out in RHEL-based distros. CentOS has really good times.
> > 
> > 
> > Any idea of a link to where I could go read about it? Debian is producing really good plot times for me. Seems odd to me as I thought Debian and Ubuntu were really close to being the same? Anyways, I’m up and running on latest Debian now and I am happy with it! Keep up the good work and also thanks for your contribution! I don’t mean to sound like I’m in here whining about my plot times. Just wanted to bring it to your attention. I didn’t know it had already been discussed.
> 
> if I may ask, where did you get debian 10 or v11? I'd like to try to see if I can replicate the difference in performance. currently ubuntu 20.04 as well.

Just get it from the Debian website. Link below. I switched from Ubuntu 20.04 back to Debian again on my plotter and things are back to normal. Running Debian 11 latest. 

https://www.debian.org/CD/netinst/

**Comment by wtfiwinomgs** [comment]
> 

i'd love to try it on debian, it seems its pretty similar to linux so not much need to relearn. from your time its around 37% performance increase which is pretty messed up, unbelievably fast.

right now bladebit I am getting around 14-15 mins ish so hope to see this drop sub 11 mins.

**Comment by RobbieL811** [comment]
> > 
> 
> i'd love to try it on debian, it seems its pretty similar to linux so not much need to relearn. from your time its around 37% performance increase which is pretty messed up, unbelievably fast.
> 
> right now bladebit I am getting around 14-15 mins ish so hope to see this drop sub 11 mins.

Did you ever try this on your system? Did you notice differences also? I'm assuming you were originally running on an Ubuntu system?

**Comment by imba-pericia** [comment]
> 
I checked Rocky Linux - + -840s, stay on it)

**Comment by zhenglcc** [comment]
我用的是epyc 7601X2 512GB 2400 RAM，当我用Ubuntu20.04的时候 大概8分钟，现在改用debian 11，只需要6分钟。

**Comment by t7aliang** [comment]
Wow , according to the disscustion here , I was greatly inspired . I plot with a ubuntu20.04 on my supermicro & EPYC before, I tried to change to Debian 11 today , but I faild after many times, That was an unsolvable network problem when I install the kernel, because I`m a Chinese, you know… Rocky Linux at last , the p.otting time was redused from 6~7 mins to 4~5mins now , I'm really excited , 244.53 seconds is my record now . Now I`m trying to delivery the plots from nvme SSD temp to multiple HDD at the same time automaticly with shell scrips. That`s a perfect method now I think. Thanks to everyone here.

**Comment by t7aliang** [comment]
> > Wow , according to the disscustion here , I was greatly inspired . I plot with an ubuntu20.04 on my supermicro & EPYC machine before, I tried to change to Debian 11 today , but I faild after many times, That was an unsolvable network problem when I install the kernel, because I am a Chinese, you know… Rocky Linux at last , the plotting time was redused from 6-7 mins to 4-5 mins now , I'm really excited , 244.53 seconds is my record now . Now I am trying to delivery the plots from nvme SSD temp to multiple HDD at the same time automaticly with shell scrips. That`s a perfect method now I think. Thanks to everyone here. And I have something interesting to share, Several times the speed from nvme SSD to HDD (Seagate EXOS ) is reaching 1.7GB/sec, 1 plot transfering compeleted only in 2mins, how could it be done ,what is going on ?? how to keep this speed ratio??
> 
> So, you saw increased plot times also with Debian? Interesting. I wonder what is slowing things down? I use the python program below to move plots from my buffer. I'm pretty sure it supports moving to multiple drives simultaneously. I can't plot fast enough to test it. If you try it, let me know if it works. It's pretty simple to setup. Works great for me.
> 
> https://github.com/maxbanton/chia-plot-mover

Sorry ,I meant , I gave up to install Debian 11, and I take Rocky Linux at last to instead of Ubuntu, and it works, time reduced.
thanks a lot to supply the mover , I'll post here after try.

**Comment by t7aliang** [comment]
> > Wow , according to the disscustion here , I was greatly inspired . I plot with an ubuntu20.04 on my supermicro & EPYC machine before, I tried to change to Debian 11 today , but I faild after many times, That was an unsolvable network problem when I install the kernel, because I am a Chinese, you know… Rocky Linux at last , the plotting time was redused from 6-7 mins to 4-5 mins now , I'm really excited , 244.53 seconds is my record now . Now I am trying to delivery the plots from nvme SSD temp to multiple HDD at the same time automaticly with shell scrips. That`s a perfect method now I think. Thanks to everyone here. And I have something interesting to share, Several times the speed from nvme SSD to HDD (Seagate EXOS ) is reaching 1.7GB/sec, 1 plot transfering compeleted only in 2mins, how could it be done ,what is going on ?? how to keep this speed ratio??
> 
> So, you saw increased plot times also with Debian? Interesting. I wonder what is slowing things down? I use the python program below to move plots from my buffer. I'm pretty sure it supports moving to multiple drives simultaneously. I can't plot fast enough to test it. If you try it, let me know if it works. It's pretty simple to setup. Works great for me.
> 
> https://github.com/maxbanton/chia-plot-mover
Hey Robbie, the mover script running smoothly on my plotter for a whole day, wonderful , it is just what I am eagering for .  The final plots are delivered correctly . Works great for me as you said. Now I have an intelligent plotter machine without manual intervention.
`01:00:28:INFO:Main thread: No plots found. Sleep for 60s
01:01:28:INFO:Main thread: No plots found. Sleep for 60s
01:02:28:INFO:Main thread: No plots found. Sleep for 60s
`

**Comment by jmhands** [comment]
performance, old version of plotter
