### ISSUE TITLE
When will the support for K33Magi K34 be updated?

### ISSUE THREAD

**Issue by Concord-us** [Chia-Network/bladebit#179]
When will the support for K33Magi K34 be updated?

**Comment by mech2you** [comment]
K33 wulde be nice

**Comment by GlenAllan888** [comment]
I’m mainly waiting for k=35 capabilities. I’m converting my farm to have the heaviest weighting of k35s out of all plot sizes and no k32s.

I wish I understood better why the Chia PoS plotter can plot any size and neither BB or MM can without such specific tuning. I guess at these accelerated performance levels every k size needs a different rebalancing.

Either way, it would be great to be able to convert the farm to k=35s at better than the snails pace of the main PoS plotter.

**Comment by PhillWalker** [comment]
K34 would be great

**Comment by jmhands** [comment]
feature is on plotting and farming roadmap
