### ISSUE TITLE
win10 bladebit run second plot stop. 

### ISSUE THREAD

**Issue by ltf722** [Chia-Network/bladebit#185]
i set -n 99 .but run second plot stop.
./bladebit -n 99 -t 11 -f 894d800eedff5bf1c87c0c184c1fa96b5470b645c2f7e148b0244df55973ac05484f3fba92999cbff92e389c88c1cbdf -c xch1dg2ylmgp8laxlmltg0unn3jpmqacqj9k5fw3957af8sa6yck8cgsc0k3hu diskplot -t1 D:\temp\ -t2 F:\temp\ E:\
![微信图片_20220509201539](https://user-images.githubusercontent.com/70614069/167408481-66b4e178-2de5-47a9-8546-df60708b1576.png)

**Comment by harold-b** [comment]
`-n` is not yet supported on the current release, as specified in the "known issues" of the release notes:

> `-n` parameters is not supported yet and results in memory leaks and other undefined behavior.

It should be ready on the next alpha release.
