### ISSUE TITLE
Cause of "Failed to obtain temp paths block size"

### ISSUE THREAD

**Issue by dan-willett** [Chia-Network/bladebit#204]
I am attempting to run bladebit 2.0.0 Alpha 2 and I am getting the following error:

Fatal Error:
Failed to obtain temp paths block size from t1: 'f:/Chia-TPlots' or f:/Chia-TPlots t2:

Please advise the cause and fix for this error message.

**Comment by harold-b** [comment]
Are you sure the paths exist? This would typically mean that the paths either don't exist, or there's a typo in there
