### ISSUE TITLE
epyc 7573x

### ISSUE THREAD

**Issue by hhdllhflower** [Chia-Network/bladebit#216]
I have a DELL R7525 server here with two **EPYC 7573X** CPUs and 512G memory. 
CPU Cores 32 *2 = 64
Base Clock 2.8GHz
Max. Boost Clock Up to 3.6GHz
This CPU has **768M L3 cache**, is there any special advantage for chia plotting? 
Is it possible to improve efficiency through parameter optimization of BladeBit software?
If you have any suggestions, please leave a message

**Comment by harold-b** [comment]
I am not sure I understand the question. Is your question about Bladebit in-ram or the disk beta?

With that system your best bet is to use bladebit in-ram (version 1.*) and throw all the threads you have at it. Make sure the destination path for the plot is a fast ssd or it can become a bottleneck.

**Comment by hhdllhflower** [comment]
> I am not sure I understand the question. Is your question about Bladebit in-ram or the disk beta?
> 
> With that system your best bet is to use bladebit in-ram (version 1.*) and throw all the threads you have at it. Make sure the destination path for the plot is a fast ssd or it can become a bottleneck.

Of course I want to use the in-ram version. My problem is that this CPU has a large L3 cache capacity compared to other CPUs.
In the README it is written that CPUs with large caches will benefit as well.
Are there specific parameters that can be optimized for such a large cache CPU?

**Comment by harold-b** [comment]
I see what you mean. No you don't have to do anything at all. What that part from the README means is that BB is written in a very cache-friendly way, which the processor will automatically take advantage of. There's nothing you need to do on your side.
