### ISSUE TITLE
Diskplot fails at Sorting F7 & Writing C Tables (v2.0.0-rc1)

### ISSUE THREAD

**Issue by reythia** [Chia-Network/bladebit#231]
BB fails silently at 'Sorting F7 & Writing C Tables'. Repeated three times with same result.

Win 11, 128GB RAM, 8TB disk

`bladebit -t 32 -f ... -c ... --verbose diskplot -b 256 --cache 100G -t1 D:/ D:/`

```
Bladebit Chia Plotter
Version      : 2.0.0-rc1
Git Commit   : efeb64d56352e40679d6bf38cf382c191c3a0dea
Compiled With: msvc 19.29.30146
...
Started plot.
Running Phase 1
...
Table 7
 Sorting      : Completed in 36.04 seconds.
 Distribution : Completed in 3.32 seconds.
 Matching     : Completed in 11.75 seconds.
 Fx           : Completed in 11.95 seconds.
Completed table 7 in 74.86 seconds with 4293182089 entries.
Table 7 I/O wait time: 0.05 seconds.
 Table 7 I/O Metrics:
  Average read throughput 3416.34 MiB ( 3582.30 MB ) or 3.34 GiB ( 3.58 GB ).
  Total size read: 65617.78 MiB ( 68805.23 MB ) or 64.08 GiB ( 68.81 GB ).
  Total read commands: 196608.
  Average write throughput 4576.19 MiB ( 4798.49 MB ) or 4.47 GiB ( 4.80 GB ).
  Total size written: 78884.79 MiB ( 82716.69 MB ) or 77.04 GiB ( 82.72 GB ).
  Total write commands: 66306.

Sorting F7 & Writing C Tables
[silent fail]
..\bladebit-v2.0.0-rc1-windows-x86-64>

```

Edit: Just to confirm, this does not happen in beta1

**Comment by harold-b** [comment]
Thanks for the info, @reythia. I identified the issue and have commits pending more testing for a minor release. If you'd like to try it, you can try the latest CI artifacts here:
https://github.com/Chia-Network/bladebit/actions/runs/3398805060

**Comment by reythia** [comment]
@harold-b Looks good! Nice job, thanks for the quick resolution. Closing this issue now.

**Comment by Acer854** [comment]
This is still happening for me frequently on 2.0.1.

bladebit -t 14 -f <f> -c <c> diskplot -a --cache 50G -t1 p:\ p:\
