### ISSUE TITLE
With a 100 GiB mode error

### ISSUE THREAD

**Issue by hitpp** [Chia-Network/bladebit#261]
With a 100 GiB temp2 cache and alternating mode
<img width="373" alt="1" src="https://user-images.githubusercontent.com/65964928/213006951-fd0c3998-882d-4415-bf85-a86da5b54ce1.png">
<img width="270" alt="2" src="https://user-images.githubusercontent.com/65964928/213007032-63b2092d-493d-4f8c-b61d-0021ac340b1b.png">
help!!!

**Comment by harold-b** [comment]
It looks like you might be using a ramdisk for temp paths, therefore you need to disable direct-io in the command line too via :
```bash
bladebit ... diskoplot ... --no-t1-direct --no-t2-direct`
```

Also, the screenshot seems to show alternating I/O is disabled (you mentioned it is enabled). Another note, If you are using the in-ram cache (with enough space) for temp2, there's no need for a ramdisk for temp2
