### ISSUE TITLE
版本V2.0.1使用报错：Unexpected argument '/datafile'

### ISSUE THREAD

**Issue by caodaye** [Chia-Network/bladebit#265]
[root@localhost bl]# ./bladebit -v -f bXXXX -c xxxx -n 1 /datafile

Fatal Error:  
Unexpected argument '/datafile'
系统环境：Debian11、centos9
都是这个报错。请问是我的格式错了么，还是版本的问题

**Comment by harold-b** [comment]
It looks like you are trying to use the cli format of v1. Download the v1 binaries if you'd like to continue using it. For v2, it changed to a subcommand format ([see README.md](https://github.com/Chia-Network/bladebit#in-ram-1)). So you need to use the `ramplot` subcommand.
