### ISSUE TITLE
报错：Failed to open plot file with error: 3

### ISSUE THREAD

**Issue by caodaye** [Chia-Network/bladebit#275]
C:\1>bladebit_cuda.exe -f XXXX-c XXXX cudaplot diskplot --cache 488G -b 64 -t1 I:\ I:\ 

Bladebit Chia Plotter
Version      : 3.0.0-alpha1-dev
Git Commit   : f269db0a7ad307514e993c335897cea7ebf46eda
Compiled With: msvc 19.33.31630

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 48
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : XXXXX
 Pool contract address : XXXX
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3070 Ti
 CUDA Compute Capability   : 8.6
 SM count                  : 48
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 5
 L2 cache size             : 4.00 MB
 L2 persist cache max size : 3.00 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 8.00 GB
  Free                     : 6.94 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 168443248640 bytes ( 160640.00 MiB or 156.88 GiB )
Total Host RAM required   : 258683772928 bytes ( 246700.07 MiB or 240.92 GiB )
GPU RAM required          : 6135181312   bytes ( 5850.96   MiB or 5.71   GiB )
Allocating buffers

Generating plot 1 / 1: 5a17048323250de081af806cfe2a7c196ef7971ca8ccf5957b8adaebeeb167ef
Plot temporary file: diskplot/plot-k32-2023-02-12-03-51-5a17048323250de081af806cfe2a7c196ef7971ca8ccf5957b8adaebeeb167ef.plot.tmp

Fatal Error:
Failed to open plot file with error: 3

我这个是格式不对，还是哪里有问题吗？

**Comment by caodaye** [comment]
配置：
CPU： E5 2697 V2 *2
内存：DDR3：512G
显卡：3070ti*1

**Comment by yxz215** [comment]
感觉你参数写错了，--compress 5 -n 1 cudaplot I:\

**Comment by harold-b** [comment]
Toy don't need to specify `-t1`. There's no temp directory for `cudaplot`, just output directories
