### ISSUE TITLE
265GB RAM System is not enough? Assertion Failed ...\CudaPlotPhase3.cu:619 CudaK32PlotPhase3AllocateBuffers() 

### ISSUE THREAD

**Issue by mech2you** [Chia-Network/bladebit#293]
![image](https://user-images.githubusercontent.com/61209759/220477451-8c1a49e4-2d9b-4449-835c-64c6903f6a9d.png)

Windows 10x64 22H2 | 3960x | 256GB | 3060 12GB

**Comment by kinomexanik** [comment]
My system froze at 245gb. At 386GB everything is fine. Try closing unnecessary services.

**Comment by mech2you** [comment]
I closed all possible services and apps... problem is the same

**Comment by mech2you** [comment]
so when i used this plotter (https://downloads.chia.net/bladebit/) and not compile it by my one it was fine

**Comment by kinomexanik** [comment]
Experiment: set compression level to 6 (--compress 6). If a plot is created, then 256gb for a raft with compression level 0 is not enough.
