### ISSUE TITLE
Assertion Failed @.../bladebit/cuda/GpuStreams.xpp:571 UploadArry(). 

### ISSUE THREAD

**Issue by mech2you** [Chia-Network/bladebit#294]
Problem in Phase 2 -> Compressing table 2 and 3

<img width="1738" alt="Screenshot from 2023-02-22 23-26-24" src="https://user-images.githubusercontent.com/61209759/220777750-3071b8b2-8e10-4a44-ad91-9675e1a5b128.png">
Linux Ubuntu 22.04 | 3960x | 256GB Ram | 3060 12GB

**Comment by mech2you** [comment]
On a clean installation Ubuntu Server 22.04.2 is the problem the same

![20230224_045859](https://user-images.githubusercontent.com/61209759/221088986-659ac621-8bd8-49da-9596-06015572d3d4.jpg)

**Comment by harold-b** [comment]
Thanks for the report. This has been fixed, but not yet pushed. Will be fixed in the next release

**Comment by harold-b** [comment]
Fixed in b40fce737fe4d72b7882e9b0cd03f1bf8230a90a
