### ISSUE TITLE
Crashes terminal with no error on linux arch

### ISSUE THREAD

**Issue by BubbleTrouble14** [Chia-Network/bladebit#295]
Crashes terminal with no error after a few seconds during allocating buffers.

Linux endeavouros, plasma KDE
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02 -    Driver Version: 525.89.02   - CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+

CPU: AMD Ryzen Threadripper PRO 3995WX 64-Cores
RAM: 256 gb
GPU: Asus Strix 3090

Bladebit Chia Plotter
Version      : 3.0.0-alpha1-dev
Git Commit   : 221fb883990dba6f0d12a9dbdd7de711de41f174
Compiled With: gcc 12.2.1

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 128
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : 8deddc091195b0df6211f2ddd9a2510758503853283123999643cc6ac73fd288890a936cc132ff5158b8430b19335a4c
 Pool public key       : b789f95fbb555369c1ad0579aa300f4076175cb53f3f91841ed6e28a512f98d2ecdbb668a338b904163cdf305798bf0b
 Benchmark mode        : enabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3090
 CUDA Compute Capability   : 8.6
 SM count                  : 82
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 2
 L2 cache size             : 6.00 MB
 L2 persist cache max size : 4.50 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 23.69 GB
  Free                     : 22.78 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 168443248640 bytes ( 160640.00 MiB or 156.88 GiB )
Total Host RAM required   : 258683772928 bytes ( 246700.07 MiB or 240.92 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

**Comment by kinomexanik** [comment]
RAM: 256 gb is not enough at compression level 0. If you specify level 6, then you will get sweetie.

**Comment by BubbleTrouble14** [comment]
Oh thanks, ill so that 😅

**Comment by kinomexanik** [comment]
C:\bladebit\bladebit_cuda.exe -n 1 --compress 0 -f -c cudaplot H:\
my system: 2х2680v2
gtx1070 8gb
386gb
1plot 13min

if --compress 6 
11min

**Comment by BubbleTrouble14** [comment]
Yes works now thx
