### ISSUE TITLE
windows 11  plot stopped suddenly

### ISSUE THREAD

**Issue by smillmiss** [Chia-Network/bladebit#298]
![image](https://user-images.githubusercontent.com/16132950/222743640-4d28367d-324b-4a70-8ac7-64ee9dcd382c.png)

I don't know why it stopped suddenly
windows 11 
version：[bladebit-v2.0.1-windows-x86-64.zip](https://github.com/Chia-Network/bladebit/releases/download/v2.0.1/bladebit-v2.0.1-windows-x86-64.zip)

**Comment by Sonix1** [comment]
Check Windows event for application error.
