### ISSUE TITLE
Error C2220 in VS 2022

### ISSUE THREAD

**Issue by mech2you** [Chia-Network/bladebit#299]
Error C2220 is comming in Visual Studio 2022. 
In \src\plotting\matching\GroupScan.cpp 125 is Error C2220
In \src\commands\CmdSimulator.cpp 174 is Error C2220
In \src\harvesting\GreenReaper.cpp 325 is Error C2220

I commented out the code in line 176 of file CMakeLists.txt. After that, the compiling process went through

![image](https://user-images.githubusercontent.com/61209759/222997665-4678cfb4-f3ff-4c13-b5fb-5fcc23e490d3.png)

**Comment by harold-b** [comment]
Thanks, for the report, but no worries about reporting build issues. We're aware of them. Just haven't gotten around to it. macOS and Windows build issues will be resolved today 👍
