### ISSUE TITLE
Failed to plot with ramfs

### ISSUE THREAD

**Issue by dpool-cc** [Chia-Network/bladebit#300]
Command:
./bladebit_cuda -f cd7c1167cdae2a8d26a6705979ec42c566bb17eed96034f91c0b0df778d154620fd917e720e5e11d941961699db3c78d -c xch6x7hf378dc5d2nu4g9n5em7zsq39xdqpwh6lk529lr24hhz6lsx0sqjkz12 -n 1 -t 16 --compress 7 cudaplot /mnt/ram

Error log:
Fatal Error:
Failed to open plot file with error: 22

Ramfs:
sudo mount tmpfs -t tmpfs -o size=150G /mnt/ram

**Comment by dpool-cc** [comment]
#284

**Comment by juelianfy** [comment]
me too
