### ISSUE TITLE
package install didn't get correct version of cmake

### ISSUE THREAD

**Issue by charbob** [Chia-Network/bladebit#316]
I'll preface with the fact that I'm a Linux beginner, so I might be missing something obvious. I was following the readme to install bladebit on my Intel NUC running ubuntu 20.04.6, but when I run "cmake ..", I'm hit with this error:

> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
> CMake 3.20 or higher is required.  You are running version 3.16.3
> -- Configuring incomplete, errors occurred!

Am I doing something wrong?

**Comment by dong3625260** [comment]
Need to upgrade to newer version

**Comment by dong3625260** [comment]
yes you can refer to https://blog.csdn.net/qq_27350133/article/details/121994229

**Comment by charbob** [comment]
Thank you, that worked. I guess my feature request would be for bladebit installation to pull the correct version of cmake, or to check which version is installed, and to retrieve the correct version if the current version is not sufficient.

**Comment by Bea07** [comment]
@dong3625260 this link is not working, could you please help on that, thank you
