### ISSUE TITLE
Can't build the latest cuda-compression source

### ISSUE THREAD

**Issue by toto99303** [Chia-Network/bladebit#319]
Hello,

I'm trying to build the latest cuda-compression source, but I got this error when running cmake ..

`CMake Error at Harvester.cmake:1 (add_library):
  Target "bladebit_harvester" links to target "CUDA::cudart_static>" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:159 (include)

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
`
What could be the problem? Thanks!

**Comment by rumas77** [comment]
Edit the "Harvester.cmake" file like so:

Replace this:
```
$<${have_cuda}: CUDA::cudart_static>
``` 
with this:
```
$<${have_cuda}:CUDA::cudart_static>
``` 
Then continue as normal:
cmake ..

**Comment by gibblinhimer** [comment]
Yep... that worked like a charm

**Comment by toto99303** [comment]
> Edit the "Harvester.cmake" file like so:
> 
> Replace this:
> 
> ```
> $<${have_cuda}: CUDA::cudart_static>
> ```
> 
> with this:
> 
> ```
> $<${have_cuda}:CUDA::cudart_static>
> ```
> 
> Then continue as normal: cmake ..

Thanks! Now it compiles fine.

**Comment by wallentx** [comment]
Thanks for reporting!
