### ISSUE TITLE
The Quality of the C9 compression level is wrong

### ISSUE THREAD

**Issue by trying2016** [Chia-Network/bladebit#331]
Use --memo --plot-id to specify Plot data to generate C7 and C9 files.

Use the following command to get quality
./bladebit_cuda validate --prove 13fcd6d98a9985204a2e1265db0aa1f80bb110479671dea7b75e64eb640bfef1 --quality 1 --cuda plot-k32-c09-2023-05-23-14-19-ef11406090 d500fb69e823e0364227b7339cbd3d2e8a0eb7cc783221cbb11981.plot
[0].hi: 0 [0].lo: 772655724832710440 [1].hi: 0 [1].lo: 1587453687530416707 req.x1: 4034804200 req.x2: 1371032182
challenge: 13fcd6d98a9985204a2e1265db0aa1f80bb110479671dea7b75e64eb640bfef1 458002bebacc3c0eee001ea07c6f432eae77460b344719b442e36fa17afe6270
 [0].hi: 0 [0].lo: 220682127248567847 [1].hi: 0 [1].lo: 224695085029697518 req.x1: 2386342838 req.x2: 1673321346
challenge: 13fcd6d98a9985204a2e1265db0aa1f80bb110479671dea7b75e64eb640bfef1 3e1063d52b9e994adac3950c4b6e7ca5bff0ccfc8380f435639c6c49dfb1a14e

./bladebit_cuda validate --prove 13fcd6d98a9985204a2e1265db0aa1f80bb110479671dea7b75e64eb640bfef1 --quality 1 --cuda plot-k32-c07-2023-05-23-14-39-ef11406090 d500fb69e823e0364227b7339cbd3d2e8a0eb7cc783221cbb11981.plot
[0].hi: 0 [0].lo: 41664163047 [1].hi: 0 [1].lo: 95413813098 req.x1: 3190776591 req.x2: 1032473874
challenge: 13fcd6d98a9985204a2e1265db0aa1f80bb110479671dea7b75e64eb640bfef1 c1bd6e754a0adae2417eb47b877fc76f132a016b700137230f1e05ef8a3564c1
 [0].hi: 0 [0].lo: 3271235689 [1].hi: 0 [1].lo: 13527824805 req.x1: 1686755598 req.x2: 1197943660
challenge: 13fcd6d98a9985204a2e1265db0aa1f80bb110479671dea7b75e64eb640bfef1 e752d6519c041c97e429718c29429ddbe7f774a392e03e9f71354ae6cf40528d

The calculation result is different

**Comment by RnMss** [comment]
The latest commit disabled C9 harvesting. Seems that C9 is completely broken.

**Comment by harold-b** [comment]
C9 has only ever been enabled for testing plotting. They are not farmable yet, and their compression values may not yet be final.
There's a warning always displayed if you select that level:
https://github.com/Chia-Network/bladebit/blob/cuda-compression/src/main.cpp#L394C35-L394C147
