### ISSUE TITLE
gpu + 128GB RAM?

### ISSUE THREAD

**Issue by kiss81** [Chia-Network/bladebit#357]
I want to replot everything to go compressed. Is 128GB ram + a GPU already possible? Any ETA? Otherwise I might consider buying an old server to go for RAM plotting.

**Comment by jmhands** [comment]
We will be announcing software availability and new features for bladebit in the Chia Discord channel bladebit-alpha. First versions should be available relatively soon. 256GB mode (completely in-memory) will remain the most efficient, fastest, and least SSD wear way to create plots
