### ISSUE TITLE
[v3.0.0] diskplot is currently disabled for compressed plotting due to a bug

### ISSUE THREAD

**Issue by ageorge95** [Chia-Network/bladebit#364]
Hi,

By try-and-error I found out that diskplot is not yet implemented for compressed plots (although a "stable" v3.0.0 version was released recently ...)

Is it possible to maybe add a note in the ReadMe to let people know that they should not waste time to prepare for plotting on a disk as that is not yet implemented ?

Also, could someone share the reported "bug" that is preventing the diskplot to function properly ? I would like to closely follow the progress on that, if possible. 

Thanks !

**Comment by JustAlias** [comment]
up

**Comment by azhe** [comment]
up

**Comment by jmhands** [comment]
yes we will be documenting which version of bladebit has issues with the various plotters, including this one for the release notes and documentation for 2.0 launch

**Comment by Fjodor42** [comment]
> yes we will be documenting which version of bladebit has issues with the various plotters, including this one for the release notes and documentation for 2.0 launch

So, given that that you closed this as "completed", where is that documentation located, @jmhands?

**Comment by haorldbchi** [comment]
Our focus is currently completely in Proof of Space 2.0 which is planned to replace the current plot format
