### ISSUE TITLE
bladebit cudaplot fatal error

### ISSUE THREAD

**Issue by hajes** [Chia-Network/bladebit#366]
debian testing

chia 2.0.0-rc3

Bladebit Chia Plotter
Version      : 3.0.0
Git Commit   : 02a8e68dcf0e971c72fc8377b89cdd081b80b843
Compiled With: gcc 9.4.0

[Global Plotting Config]
 Will create 5 plots.
 Thread count          : 48
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : true
 Farmer public key     : ....
 Pool contract address : ....
 Compression Level     : 5
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
Selected cuda device 0 : NVIDIA GeForce RTX 3060 Ti
 CUDA Compute Capability   : 8.6
 SM count                  : 38
 Max blocks per SM         : 16
 Max threads per SM        : 1536
 Async Engine Count        : 2
 L2 cache size             : 3.00 MB
 L2 persist cache max size : 2.25 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 7.79 GB
  Free                     : 7.62 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 90240524288  bytes ( 86060.07  MiB or 84.04  GiB )
Intermediate RAM required : 2999001088   bytes ( 2860.07   MiB or 2.79   GiB )
Host RAM required         : 141733920768 bytes ( 135168.00 MiB or 132.00 GiB )
Total Host RAM required   : 231974445056 bytes ( 221228.07 MiB or 216.04 GiB )
GPU RAM required          : 6140243968   bytes ( 5855.79   MiB or 5.72   GiB )
Allocating buffers

Generating plot 1 / 5: f4d649991066a6d1a36854f1ff395fddcf209fd53097d4897881b993a530717c
Plot temporary file: --temp1/plot-k32-c05-2023-08-05-21-49-f4d649991066a6d1a36854f1ff395fddcf209fd53097d4897881b993a530717c.plot.tmp

STDERR: 

STDERR: Fatal Error:  

STDERR: Failed to open plot file with error: 2

**Comment by hajes** [comment]
installed nvidia 535 driver, still same error.

**Comment by hajes** [comment]
tried alpha4.4 baladebit, and it works. I noticed that official Chia 2.0.0-rc3 uses incorrect/non-existent directory

`-t /c-tmp/ -d /c-tmp/`

yet it uses 

`Plot temporary file: --temp1/plot-k32-...`

**Comment by TheSpearman** [comment]
Please show the full command that you're trying use (minus your keys). I've found it was sensitive to the option order and could give such errors if they were in the wrong sequence.

**Comment by hajes** [comment]
it was a driver mismatch. nVidia 535.xxx series solved this issue.
