### ISSUE TITLE
Latest 3.0.0 build does not allow device specification

### ISSUE THREAD

**Issue by XCHSystems** [Chia-Network/bladebit#368]
I have tried both the -d and --device option, with two GPUs, GPU0 and GPU1, even if I specify GPU1 it always uses GPU0 so clearly this is not working

**Comment by XCHSystems** [comment]
I found the issue, it is not documented in the --help

but the -d option has to be specified in between cudaplot and the target folder

**Comment by nbit99** [comment]
I have tow GPUS,
I need the -d too!

**Comment by harold-b** [comment]
It's documented [here](https://github.com/Chia-Network/bladebit#usage)

The format is `bladebit <GLOBAL_OPTIONS> <sub_command> <COMMAND_OPTIONS>.`
where `-d` is part of the subcommand `cudaplot` so it must come after the subcommand.

`GLOBAL_OPTIONS` must go before the `sub_command`, then any option following a `sub_command` are considered options belonging to that `sub_command`.

**Comment by harold-b** [comment]
You can get command-specific help test with `bladebit_cuda help <command>` or (depending on the command `bladebit_cuda <command> --help`
