### ISSUE TITLE
Doesn't  support Debian 10?

### ISSUE THREAD

**Issue by maogo** [Chia-Network/bladebit#371]
./bladebit_cuda: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./bladebit_cuda)

**Comment by hajes** [comment]
Debian 10 has got obsolete cmake or something like that...you need at least Debian 11 or 12. I was running Debian testing, but plotting was slow. Debian has got issues with drivers on my old server

**Comment by wallentx** [comment]
https://endoflife.date/debian
We generally don't support things once they hit their EOL for security updates.
