### ISSUE TITLE
Unable to use taskset for Bladebit on Rocky Linux 9.2

### ISSUE THREAD

**Issue by Jason-2048** [Chia-Network/bladebit#392]
**Issue Description:**

I am encountering an issue with Rocky Linux 9.2 where I am unable to use `taskset` to set the number of threads for Bladebit. This issue is significant because manually specifying the number of threads can significantly reduce interference with Bladebit's performance, especially when transferring plot files via SFTP.

**Environment:**

- Operating System: Rocky Linux 9.2
- Bladebit Version: 3.0.0

**Expected Behavior:**

Bladebit does not appear to be affected by the `taskset` command, and it continues to use the default CPU core allocation, resulting in a significant drop in performance during SFTP transfers.

Thank you for your assistance in resolving this problem.

**Comment by harold-b** [comment]
You'll have to use `--no-cpu-affinity` and (if needed) `--no-numa` for bladebit to not handle its own CPU core affinity.
