### ISSUE TITLE
Allocation buffer overrun.

### ISSUE THREAD

**Issue by ToniMarti** [Chia-Network/bladebit#399]
Bladebit Chia Plotter
Version      : 3.1.0-beta1
Git Commit   : 076eba490f1c08b3a7bf10ea0a08f80be758c7b9
Compiled With: msvc 19.29.30151

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 16
 Warm start enabled    : true
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : 
 Pool public key       : 
 Benchmark mode        : disabled

[Bladebit Disk Plotter]
 Heap size      : 3.37 GiB ( 3445.94 MiB )
 Cache size     : 54.00 GiB ( 55296.00 MiB )
 Bucket count   : 256
 Alternating I/O: false
 F1  threads    : 16
 FP  threads    : 16
 C   threads    : 16
 P2  threads    : 8
 P3  threads    : 16
 I/O threads    : 1
 Temp1 block sz : 512
 Temp2 block sz : 4096
 Temp1 path     : D:\ploter1
 Temp2 path     : H:\ploter2
 I/O metrices enabled.
 Allocating memory
Warm start: Pre-faulting memory pages...
Memory initialized.

Generating plot 1 / 1: 46e5391d77d3f95512a9cd6f6fa11603ecccff92c5a516ccf53cc5e5ce85b0a1
Plot temporary file: I:\PLOTS/plot-k32-2023-09-05-20-21-46e5391d77d3f95512a9cd6f6fa11603ecccff92c5a516ccf53cc5e5ce85b0a1.plot.tmp

Started plot.
Running Phase 1
Table 1: F1 generation
Generating f1...

Compressing tables 2 and 3.

Fatal Error:
Allocation buffer overrun.

Winwdows home 10
AMD Ryzen Theaddriper 1950x   Ram 64 gb

**Comment by jmhands** [comment]
bladebit disk not yet supported in 3.1 beta1. There is a 16GB cudaplot mode with `./bladebit_cuda -f xxx -c xxx cudaplot --disk-16 -t1 /mnt/ssd /mnt/final`
