### ISSUE TITLE
CUDA error: 700 (0x2bc) cudaErrorIllegalAddress : an illegal memory access was encountered

### ISSUE THREAD

**Issue by shmox75** [Chia-Network/bladebit#402]
Generating F1
Finished F1 in 174.75 seconds.
Table 2 completed in 361.52 seconds with 4294953915 entries.
Table 3 completed in 503.28 seconds with 4294928769 entries.
Table 4 completed in 553.26 seconds with 4294895972 entries.
Table 5 completed in 551.02 seconds with 4294850964 entries.
Table 6 completed in 484.31 seconds with 4294651149 entries.
CUDA error: 700 (0x2bc) cudaErrorIllegalAddress : an illegal memory access was encountered

*** Panic!!! *** Fatal Error:
CUDA error cudaErrorIllegalAddress : an illegal memory access was encountered.
0x00007FF627B58E22 @ <unknown>::<unknown>
0x00007FF627C59499 @ <unknown>::<unknown>
0x00007FF627C77A8D @ <unknown>::<unknown>
0x00007FF627C79BF1 @ <unknown>::<unknown>
0x00007FF627C78F4A @ <unknown>::<unknown>
0x00007FF627C7AABF @ <unknown>::<unknown>
0x00007FF627C7B139 @ <unknown>::<unknown>
0x00007FF627B3F0BF @ <unknown>::<unknown>
0x00007FF627CE4C8C @ <unknown>::<unknown>
0x00007FFF9B5026AD @ <unknown>::BaseThreadInitThunk()
0x00007FFF9C62AA68 @ <unknown>::RtlUserThreadStart()

Windows 11, 16GB RAM, RTX 3070, bladebit-cuda-v3.1.0-beta1-windows-x86-64

**Comment by jmhands** [comment]
do you get this error on every plot or just intermittent failure?

**Comment by shmox75** [comment]
> do you get this error on every plot or just intermittent failure?

Always, never passed this error

**Comment by shmox75** [comment]
I have found what was causing this issue:
It was MSI Afterburner that was runing in the background and tweaking my GPU, undervolting etc..
So after disabling MSI Afterburner, the ploting process run successfully.
Closing the issue.
