### ISSUE TITLE
Recommand plot options?

### ISSUE THREAD

**Issue by nicezic** [Chia-Network/bladebit#407]
* CPU : AMD Ryzen 9 5950X 16-Core Processor ( 32 threads )
* GPU : GTX 1070 ( 8GB )
* RAM : 128 GB
* SSD : 1TB for tmp plotting
* OS : Ubuntu 20.04

Can you recommand plot options?

**Comment by jmhands** [comment]
to test `./bladebit_cuda -f <farmer key> -c <contract address> -z 1 -n 1 cudaplot --disk-128 -t1 /mnt/ssd /mnt/ssd`
and check with `./bladebit_cuda check -n 100 /mnt/ssd/xxx.plot`
