### ISSUE TITLE
Bladebit 3.1.0-beta sometimes double the time for one plot or more

### ISSUE THREAD

**Issue by secco04** [Chia-Network/bladebit#409]
Hi have to report some issues with my system 

ryzen7 7800X3D
128GB RAM
1x1TB tmp nvme
gtx 1080

my command to plot with is 
`    .\bladebit_cuda.exe  -z 4 -f farmerkey -c contract  cudaplot --disk-128 -t1 l:\temp\  l:\temp\1\
`
in a powershell loop to dont have problems with 128+ plots error 

my result normally is:
` Bladebit Chia Plotter
Version      : 3.1.0-beta1
Git Commit   : 076eba490f1c08b3a7bf10ea0a08f80be758c7b9
Compiled With: msvc 19.29.30151

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 16
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : 
 Pool contract address : 
 Compression Level     : 4
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
 Host RAM        : 127 GiB
 Direct transfers: true

Selected cuda device 0 : NVIDIA GeForce GTX 1080
 CUDA Compute Capability   : 6.1
 SM count                  : 20
 Max blocks per SM         : 32
 Max threads per SM        : 2048
 Async Engine Count        : 5
 L2 cache size             : 2.00 MB
 L2 persist cache max size : 0.00 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 8.00 GB
  Free                     : 7.02 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 92051827920  bytes ( 87787.46  MiB or 85.73  GiB )
Intermediate RAM required : 4362149888   bytes ( 4160.07   MiB or 4.06   GiB )
Host RAM required         : 28319940608  bytes ( 27008.00  MiB or 26.38  GiB )
Total Host RAM required   : 120371768528 bytes ( 114795.46 MiB or 112.10 GiB )
GPU RAM required          : 6139441152   bytes ( 5855.03   MiB or 5.72   GiB )
Allocating buffers...
Table pairs allocated as pinned: false

Generating plot 1 / 1: 5b31db7c2d978d53aa30c60d7dfdc1fc2f0a81ccefd9e473ce26ffe6ffe194aa
Plot temporary file: l:\temp\1\plot-k32-c04-2023-09-12-18-54-5b31db7c2d978d53aa30c60d7dfdc1fc2f0a81ccefd9e473ce26ffe6ffe194aa.plot.tmp

Generating F1
Finished F1 in 6.65 seconds.
Table 2 completed in 24.46 seconds with 4294827575 entries.
Table 3 completed in 38.76 seconds with 4294684619 entries.
Table 4 completed in 62.86 seconds with 4294262814 entries.
Table 5 completed in 49.92 seconds with 4293441678 entries.
Table 6 completed in 44.92 seconds with 4291773671 entries.
Table 7 completed in 34.99 seconds with 4288516371 entries.
Finalizing Table 7
Finalized Table 7 in 14.45 seconds.
Completed Phase 1 in 277.48 seconds
Marked Table 6 in 11.08 seconds.
Marked Table 5 in 11.43 seconds.
Marked Table 4 in 11.08 seconds.
Marked Table 3 in 10.89 seconds.
Completed Phase 2 in 44.48 seconds
Compressing Table 2 and 3...
 Step 1 completed step in 21.95 seconds.
 Step 2 completed step in 21.18 seconds.
Completed table 2 in 43.13 seconds with 3439347158 / 4294684619 entries ( 80.08% ).
Compressing tables 3 and 4...
 Step 1 completed step in 18.71 seconds.
 Step 2 completed step in 22.66 seconds.
 Step 3 completed step in 22.59 seconds.
Completed table 3 in 63.97 seconds with 3465015973 / 4294262814 entries ( 80.69% ).
Compressing tables 4 and 5...
 Step 1 completed step in 19.55 seconds.
 Step 2 completed step in 22.62 seconds.
 Step 3 completed step in 22.67 seconds.
Completed table 4 in 64.84 seconds with 3530953213 / 4293441678 entries ( 82.24% ).
Compressing tables 5 and 6...
 Step 1 completed step in 18.11 seconds.
 Step 2 completed step in 22.58 seconds.
 Step 3 completed step in 23.61 seconds.
Completed table 5 in 64.30 seconds with 3710050019 / 4291773671 entries ( 86.45% ).
Compressing tables 6 and 7...
 Step 1 completed step in 18.24 seconds.
 Step 2 completed step in 24.36 seconds.
 Step 3 completed step in 27.49 seconds.
Completed table 6 in 70.11 seconds with 4288516371 / 4288516371 entries ( 100.00% ).
Serializing P7 entries
Completed serializing P7 entries in 12.30 seconds.
Completed Phase 3 in 318.66 seconds
Completed Plot 1 in 640.62 seconds ( **10.68** minutes )

l:\temp\4\plot-k32-c04-2023-09-12-18-54-5b31db7c2d978d53aa30c60d7dfdc1fc2f0a81ccefd9e473ce26ffe6ffe194aa.plot.tmp -> l:\temp\4\plot-k32-c04-2023-09-12-18-54-5b31db7c2d978d53aa30c60d7dfdc1fc2f0a81ccefd9e473ce26ffe6ffe194aa.plot
Completed writing plot in 5.23 seconds
Final plot table pointers:
 Table 1:                0 ( 0x0000000000000000 )
 Table 2:       1288275684 ( 0x000000004cc986e4 )
 Table 3:      10230915609 ( 0x0000000261cf6219 )
 Table 4:      24316008084 ( 0x00000005a958d694 )
 Table 5:      38669132259 ( 0x0000000900dc21e3 )
 Table 6:      53750269359 ( 0x0000000c83c405af )
 Table 7:      71182844334 ( 0x0000001092d401ae )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1719508 ( 0x00000000001a3cd4 )
 C 3    :          1719684 ( 0x00000000001a3d84 )

Final plot table sizes:
 Table 1: 0.00 MiB
 Table 2: 8528.37 MiB
 Table 3: 13432.59 MiB
 Table 4: 13688.21 MiB
 Table 5: 14382.49 MiB
 Table 6: 16625.00 MiB
 Table 7: 16870.63 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1226.96 MiB
`

and after some uptime/ploting hous i get double the time for one plot 

`
Bladebit Chia Plotter
Version      : 3.1.0-beta1
Git Commit   : 076eba490f1c08b3a7bf10ea0a08f80be758c7b9
Compiled With: msvc 19.29.30151

[Global Plotting Config]
 Will create 1 plots.
 Thread count          : 16
 Warm start enabled    : false
 NUMA disabled         : false
 CPU affinity disabled : false
 Farmer public key     : 
 Pool contract address : 
 Compression Level     : 3
 Benchmark mode        : disabled

[Bladebit CUDA Plotter]
 Host RAM        : 127 GiB
 Direct transfers: true

Selected cuda device 0 : NVIDIA GeForce GTX 1080
 CUDA Compute Capability   : 6.1
 SM count                  : 20
 Max blocks per SM         : 32
 Max threads per SM        : 2048
 Async Engine Count        : 5
 L2 cache size             : 2.00 MB
 L2 persist cache max size : 0.00 MB
 Stack Size                : 1.00 KB
 Memory:
  Total                    : 8.00 GB
  Free                     : 7.02 GB

Allocating buffers (this may take a few seconds)...
Kernel RAM required       : 92051827920  bytes ( 87787.46  MiB or 85.73  GiB )
Intermediate RAM required : 4362149888   bytes ( 4160.07   MiB or 4.06   GiB )
Host RAM required         : 28319940608  bytes ( 27008.00  MiB or 26.38  GiB )
Total Host RAM required   : 120371768528 bytes ( 114795.46 MiB or 112.10 GiB )
GPU RAM required          : 6139441152   bytes ( 5855.03   MiB or 5.72   GiB )
Allocating buffers...
Table pairs allocated as pinned: false

Generating plot 1 / 1: dd6ca6a96a81ec7f175ac2a9b094a654296c941a1f84321f714d126fdc33725f
Plot temporary file: l:\temp\2\plot-k32-c03-2023-09-12-19-26-dd6ca6a96a81ec7f175ac2a9b094a654296c941a1f84321f714d126fdc33725f.plot.tmp

Generating F1
Finished F1 in 14.68 seconds.
Table 2 completed in 47.41 seconds with 4294932693 entries.
Table 3 completed in 74.53 seconds with 4294851696 entries.
Table 4 completed in 136.37 seconds with 4294658916 entries.
Table 5 completed in 99.61 seconds with 4294296783 entries.
Table 6 completed in 87.10 seconds with 4293591081 entries.
Table 7 completed in 61.83 seconds with 4292192352 entries.
Finalizing Table 7
Finalized Table 7 in 52.03 seconds.
**Completed Phase 1 in 574.51 seconds**
Marked Table 6 in 18.27 seconds.
Marked Table 5 in 18.29 seconds.
Marked Table 4 in 18.21 seconds.
Marked Table 3 in 18.35 seconds.
Completed Phase 2 in 73.13 seconds
Compressing Table 2 and 3...
 Step 1 completed step in 42.87 seconds.
 Step 2 completed step in 40.29 seconds.
Completed table 2 in 83.16 seconds with 3439669515 / 4294851696 entries ( 80.09% ).
Compressing tables 3 and 4...
 Step 1 completed step in 43.68 seconds.
 Step 2 completed step in 49.10 seconds.
 Step 3 completed step in 42.94 seconds.
Completed table 3 in 135.73 seconds with 3465627861 / 4294658916 entries ( 80.70% ).
Compressing tables 4 and 5...
 Step 1 completed step in 42.63 seconds.
 Step 2 completed step in 50.41 seconds.
 Step 3 completed step in 47.84 seconds.
Completed table 4 in 140.88 seconds with 3532112707 / 4294296783 entries ( 82.25% ).
Compressing tables 5 and 6...
 Step 1 completed step in 45.47 seconds.
 Step 2 completed step in 61.61 seconds.
 Step 3 completed step in 56.34 seconds.
Completed table 5 in 193.20 seconds with 3712133784 / 4293591081 entries ( 86.46% ).
Compressing tables 6 and 7...
 Step 1 completed step in 45.06 seconds.
 Step 2 completed step in 56.76 seconds.
 Step 3 completed step in 51.47 seconds.
Completed table 6 in 153.29 seconds with 4292192352 / 4292192352 entries ( 100.00% ).
Serializing P7 entries
Completed serializing P7 entries in 24.33 seconds.
Completed Phase 3 in 730.60 seconds
Completed Plot 1 in 1378.24 seconds ( 22.97 minutes )

l:\temp\1\plot-k32-c03-2023-09-12-19-26-dd6ca6a96a81ec7f175ac2a9b094a654296c941a1f84321f714d126fdc33725f.plot.tmp -> l:\temp\1\plot-k32-c03-2023-09-12-19-26-dd6ca6a96a81ec7f175ac2a9b094a654296c941a1f84321f714d126fdc33725f.plot
Completed writing plot in 0.51 seconds
Final plot table pointers:
 Table 1:                0 ( 0x0000000000000000 )
 Table 2:       1289381156 ( 0x000000004cda6524 )
 Table 3:      11957736660 ( 0x00000002c8bc94d4 )
 Table 4:      26045318310 ( 0x00000006106c04a6 )
 Table 5:      40403154435 ( 0x0000000968373603 )
 Table 6:      55492766385 ( 0x0000000ceba06ab1 )
 Table 7:      72940284735 ( 0x00000010fb946b3f )
 C 1    :             4096 ( 0x0000000000001000 )
 C 2    :          1720980 ( 0x00000000001a4294 )
 C 3    :          1721156 ( 0x00000000001a4344 )

Final plot table sizes:
 Table 1: 0.00 MiB
 Table 2: 10174.14 MiB
 Table 3: 13434.96 MiB
 Table 4: 13692.70 MiB
 Table 5: 14390.58 MiB
 Table 6: 16639.25 MiB
 Table 7: 16885.09 MiB
 C 1    : 1.64 MiB
 C 2    : 0.00 MiB
 C 3    : 1228.01 MiB
`

**Comment by jmhands** [comment]
Most likely your SSD, what SSD are you using?

**Comment by secco04** [comment]
I solved it by splitting the temp to 2 nvme.... Maybe theyre dieing
