### ISSUE TITLE
fatal Error when trying to make more than 1 plot

### ISSUE THREAD

**Issue by Drhicom** [Chia-Network/bladebit#419]
Using  bladebit_cuda.exe 3.1.0-rc2, When using this string it stops after the first plot, and gives the fatal Error .   bladebit_cuda -f <key> -c <contractadress> -n 3  --compress 7 cudaplot --disk-128 -t1 F:\nvme\  E:\plots\ --check 100 --check-threshold 0.8   If I take off the --check 100 --check-threshold 0.8  from the end it makes all 3 plots.

![2023-09-25_173534](https://github.com/Chia-Network/bladebit/assets/81637574/d017415c-4ff5-4ab7-98ef-52ac29372217)

**Comment by Ron-ski** [comment]
Try moving the check commands directly after cudaplot.

**Comment by Drhicom** [comment]
![image](https://github.com/Chia-Network/bladebit/assets/81637574/8c3529d4-25bf-45ee-8538-e745c1a908cb)

**Comment by Drhicom** [comment]
Here is the string you suggested, putting the check right behind cudaplot
C:\bb_rc2>.\bladebit_cuda.exe -t 16 -f ffffff  -c cccccc -n 2 -z 7 cudaplot check 100 check-threshold0.8 F:\nvme\

So this is run with 256gb of system ram, if I remove the check staements it completes the plots.

**Comment by Drhicom** [comment]
With the help from Ronski, he debuged the string I had copied from Discord, which didn't have a space before the 0.8.

C:\bb_rc2>.\bladebit_cuda.exe -t 16 -f fffff -c ccccc -n 2 -z 7 cudaplot --check 100 --check-threshold 0.8 g:\plots\ 
This made two plots, with the check

Thank You Ronski!!!

**Comment by Drhicom** [comment]
Thanks again Ronski
