### ISSUE TITLE
Simulate command missing -d --device parameter yielding error

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/bladebit#432]
Reported by Valerian in discord (https://discord.com/channels/1034523881404370984/1034870571864948777/1161720918243020810)

The -d parameter is not included in the simulate command (https://github.com/Chia-Network/bladebit/blob/master/src/commands/CmdSimulator.cpp#L68)

After review the -d flag is provided in the simulate command help (https://github.com/Chia-Network/bladebit/blob/master/src/commands/CmdSimulator.cpp#L524)

Resolution - either include the -d flag in the simulate command or remove it from the help while adding a note that the default device will be used.

Error `Unexpected argument '1'`

Attempting command formats:
```
./bladebit_cuda -t 14 simulate -d 1 -n 1000 -p 4 [plot]
./bladebit_cuda -t 14 simulate --device 1 -n 1000 -p 4 [plot]
./bladebit_cuda -t 14 -d 1 simulate -n 1000 -p 4 [plot]
./bladebit_cuda -t 14 --device 1 simulate -n 1000 -p 4 [plot]
```

**Comment by harold-b** [comment]
Fixed in e7734ea
