### ISSUE TITLE
-n -1 for infinite plot creation

### ISSUE THREAD

**Issue by malventano** [Chia-Network/bladebit#52]
Along with [standard plot names](https://github.com/harold-b/bladebit/pull/21), another tweak to be consistent with the other Clia plotters would be to allow -n -1 for infinite plot creation.

**Comment by mocksoul** [comment]
-n 999999 works for me

**Comment by malventano** [comment]
> -n 999999 works for me

That works for me as well, but this issue is about being consistent with the command line inputs of other plotters. Also, -n 999999 would only run for a year, not infinitely :).

**Comment by jayhohoho2019** [comment]
It appears that the larger the -n the longer it takes to complete each plot.  On my system -n 600 gives me 7 min 15 seconds but -n 800 the per plot time increased to almost 8.5 min.  All else is equal on the system.  Have any of you noticed on your systems?

Other than that I agree -n -1 should keep plotting indefinitely.

**Comment by grobalt** [comment]
confirmed ... setting to -n 2000 adds 3 minutes -> doubling the time ... seems to be a bug

**Comment by mocksoul** [comment]
> It appears that the larger the -n the longer it takes to complete each plot. On my system -n 600 gives me 7 min 15 seconds but -n 800 the per plot time increased to almost 8.5 min. All else is equal on the system. Have any of you noticed on your systems?
> 
> Other than that I agree -n -1 should keep plotting indefinitely.

yep, i can confirum it too. After the more plot bladebit makes the more time it takes to calculate them. After restarting it works perfectly again

**Comment by malventano** [comment]
Are you guys sure you're not just seeing lower plot times for plots after the first one? I've let bladebit run for months on a system and saw zero change to plot speed. There are other (non-bladebit) factors that can slow a system down after a few plots.

**Comment by mocksoul** [comment]
Yes. I am sure bladebit slows down after 50+ plots done.
After restarting bladebit only speed recovers immidiately.

**Comment by jmhands** [comment]
this is now implemented
