### ISSUE TITLE
I wish I can provide a list of final plot paths

### ISSUE THREAD

**Issue by xorinox** [Chia-Network/bladebit#53]
Hello, I wished I could provide a list of final plot paths that are used by the plotter (maybe round robin) when -n greater 1 to store the final plot file. On my system the plotter finishes a plot every 5-7 minutes. Storing one K32 onto HDD takes longer than 5-7 minutes, which means the second plot created by bladebit is finished before the previous was stored to HDD. The plotter will now attempt to save the second file onto the HDD also, which makes things even slower.

If I can pass a list of final plots path, and the plotter uses a different one for new plot, the issue goes away. It also mitigates the need of  buffer to store all newly created plots, from which then some kind of script is moving the plots from buffer to HDDs.

**Comment by baturman** [comment]
This is actually needed a lot when gpu plotting involved.

**Comment by harold-b** [comment]
> This is actually needed a lot when gpu plotting involved.

This has already been implemented in the cudaplot alpha. Just specify more than one output pTh at the end of the command line.
