### ISSUE TITLE
Difference between --pool-key and --pool-contract options

### ISSUE THREAD

**Issue by mmmogh** [Chia-Network/bladebit#74]
What is the difference between the `--pool-key` and `--pool-contract` options? If you would like to farm pool plots, which of the two options should you use?

**Comment by colbyboles** [comment]
You want to use `--pool-contract`, `--pool-key `is need for "OG" plots, even though it can't actually be used for pooling. Just make sure you use the correct contract address for your NFT via `chia plotnft show`.
